# .github/workflows/ci.yml
name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure
      run: cmake -S . -B build -DCMAKE_CXX_STANDARD=23 -DBUILD_EXAMPLES=ON
    - name: Build
      run: cmake --build build -j
    - name: Test
      run: ./build/bykey_tests
    - name: Run Examples
      run: |
        ./build/lc_0049_group_anagrams
        ./build/lc_0347_top_k_frequent
        ./build/lc_0697_degree_of_array
        ./build/lc_0350_intersection_ii
        ./build/lc_0242_valid_anagram
        ./build/lc_1331_rank_transform
