name: release
on:
  push:
    tags: ["v*"]

jobs:
  build-test-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Tooling
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake g++ rpm

      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_CXX_STANDARD=23 -DBUILD_TESTING=ON -DBUILD_EXAMPLES=ON

      - name: Build
        run: cmake --build build -j

      - name: Test
        run: ctest --test-dir build --output-on-failure

      - name: Package artifacts
        run: cmake --build build --target package

      - name: Assemble release payload
        run: |
          set -euo pipefail
          VERSION_TAG="${GITHUB_REF_NAME}"
          VERSION_CLEAN="${VERSION_TAG#v}"
          cp include/by-key/by_key.hpp single-header-by_key.hpp
          TAR_PATH=$(find build -maxdepth 1 -name "bykey-${VERSION_CLEAN}*.tar.gz" | head -n1)
          cp "${TAR_PATH}" "bykey-${VERSION_TAG}.tar.gz"
          RPM_PATH=$(find build -maxdepth 1 -name "bykey-${VERSION_CLEAN}*.rpm" | head -n1)
          RPM_RENAMED="bykey-${VERSION_CLEAN}.rpm"
          cp "${RPM_PATH}" "${RPM_RENAMED}"
          echo "RPM_UPLOAD=${RPM_RENAMED}" >> "${GITHUB_ENV}"

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            bykey-${{ github.ref_name }}.tar.gz
            single-header-by_key.hpp
            ${{ env.RPM_UPLOAD }}
