# .github/workflows/release.yml
name: release
on:
  push:
    tags: ["v*"]

jobs:
  build-test-release:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configure
      run: cmake -S . -B build -DCMAKE_CXX_STANDARD=23 -DBUILD_TESTING=ON -DBUILD_EXAMPLES=ON

    - name: Build
      run: cmake --build build -j

    - name: Test
      run: ctest --test-dir build --output-on-failure

    - name: Package headers
      run: |
        tar -czf bykey-${GITHUB_REF_NAME}.tar.gz include/
        cp include/by-key/by_key.hpp single-header-by_key.hpp

    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        generate_release_notes: true
        files: |
          bykey-${{ github.ref_name }}.tar.gz
          single-header-by_key.hpp